apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: anpnc53fn-go 
  janus-idp.io/tekton: anpnc53fn-go
  backstage.io/kubernetes-id: anpnc53fn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: anpnc53fn-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  